/*
 * This file has been generated by the @reason-id/recollect powered by OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://github.com/reason-id/recollect
 *

 *)

val delete_order : order_id:string -> unit Lwt.t
val get_inventory : unit -> (string * int32) list Lwt.t
val get_order_by_id : order_id:int64 -> Order.t Lwt.t
val place_order : body:Order.t -> Order.t Lwt.t
