/*
 * This file has been generated by the @reason-id/recollect powered by OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://github.com/reason-id/recollect
 *

 * Schema Api_response.t : Describes the result of uploading an image resource
 *)

type t = {
    code: int32 option [@default None];
    _type: string option [@default None];
    message: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Describes the result of uploading an image resource *)
let create () : t = {
    code = None;
    _type = None;
    message = None;
}

