/*
 * This file has been generated by the @reason-id/recollect powered by OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://github.com/reason-id/recollect
 *

 * Schema Tag.t : A tag for a pet
 *)

type t = {
    id: int64 option [@default None];
    name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** A tag for a pet *)
let create () : t = {
    id = None;
    name = None;
}

